---
PERSISTENT_IDENTIFIERS:
- doi:
    source: https://www.doi.org/
    date_added: 2020-03-22
    added_by: anusuriya
- handle:
    source: https://www.handle.net/
    date_added: 2020-03-22
    added_by: anusuriya
- ark:
    source: https://n2t.net/e/ark_ids.html
    date_added: 2020-03-22
    added_by: anusuriya
- purl:
    source: http://www.purlz.org/
    date_added: 2020-03-22
    added_by: anusuriya
- lsid:
    source: http://www.lsid.info/
    date_added: 2020-03-22
    added_by: anusuriya
- urn:
    source: https://tools.ietf.org/html/rfc8141
    date_added: 2020-03-22
    added_by: anusuriya
- orcid:
    source: https://orcid.org/
    date_added: 2020-03-22
    added_by: anusuriya
- isni:
    source: http://www.isni.org/
    date_added: 2020-03-22
    added_by: anusuriya